import { URL_APIC } from "../../../../lib/services.js";
import { obtenerDatos } from "../../funciones/Solicitudes.js";
const empresa_id = JSON.parse(localStorage.getItem("yofinanciero"))[0].empresa.idempresa;

/**
 * Función para obtener el Numero de la la última transacción registrada y asignarla a un input.
 * @param {Element} input - Elemento input donde se asignará el valor.
 * @returns
 */
export const ultimaTransaccion = async (input) => {
    const dato = await obtenerDatos(`${URL_APIC}api/listatransacciones/${empresa_id}`);
    if (dato) {
        if (dato.length > 0) {
            const nTrsn = parseInt(dato[0].ntransaccion) + 1;
            input.value = nTrsn;
        } else {
            input.value = 1;
        }
    } else {
        input.removeAttribute("name");
        input.value = "ocurrió un error";
    }
}

export const formularioTransaccion = [
    {
        id: "transaccion_codigo",
        label: "N° transacción",
        forma: "input",
        tipo: "text",
        nombre: "codigo",
        required: true,
        readonly: "crear",
        accionload: ultimaTransaccion,
        n_registro: "ntransaccion",
        iclear: "false",
    },
    {
        id: "transaccion_fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "date",
        required: true
    },
    {
        id: "transaccion_tipo_cambio",
        label: "Tipo de cambio",
        forma: "select",
        origen: `${URL_APIC}api/listatipodecambio/${empresa_id}`, 
        llaves: { id: "id", detalle: [["fecha", "date"], "dolar", "ufv"] },
        nombre: "tipodecambio",
        required: true,
        n_registro: "tipocambio",
    },
    {
        id: "transaccion_tipo_asiento",
        label: "Tipo de asiento",
        forma: "select",
        origen: `${URL_APIC}api/creartipoasientolista/${empresa_id}`, 
        llaves: { id: "id", detalle: "nombre"},
        // origen: `${URL_APIC}api/tipotransaccion`, 
        // llaves: { id: "0", sid:"1", detalle: "1"},
        // llaves: { id: "idtipotransaccion", sid:"nombre", detalle: "nombre"},
        nombre: "tipotransaccion",
        required: true,
        // n_registro: "ttransaccion",
        n_registro: "idtipotransaccion",
    },
    {
        id: "transaccion_glosa",
        label: "Glosa",
        forma: "textarea",
        nombre: "descripcion",
        filas: 2,
        required: true,
        n_registro: "glosa",
    },
    {
        id: "transaccion_gestion",
        label: "Gestión",
        forma: "select",
        origen: `${URL_APIC}api/gestionlista/${empresa_id}`, 
        llaves: { id: "id", detalle: "gestion"},
        nombre: "gestion",
        required: true,
        editar: true,
    },
];

export const formularioDetalleTr = [
    // {
    //     id: "transacciondetalle_orden",
    //     label: "Orden",
    //     forma: "input",
    //     tipo: "number",
    //     nombre: "orden",
    //     // intervalo: "any",
    //     // required: true,
    //     // valor: "0",
    //     // valori: "0",
    // },
    {
        id: "transacciondetalle_cuenta",
        label: "Cuenta",
        forma: "select",
        origen: `${URL_APIC}api/milistaplanes/${empresa_id}`, 
        llaves: { id: "id", detalle: ["numero", "plan"] },
        nombre: "plandecuenta",
        required: true,
        n_registro: "idplan",
    },
    {
        id: "transacciondetalle_debe",
        label: "DEBE",
        forma: "input",
        tipo: "number",
        nombre: "debe",
        intervalo: "any",
        required: true,
        valor: "0",
        valori: "0",
    },
    {
        id: "transacciondetalle_haber",
        label: "HABER",
        forma: "input",
        tipo: "number",
        nombre: "haber",
        intervalo: "any",
        required: true,
        valor: "0",
        valori: "0",
    },
    {
        id: "transaccion_nota",
        label: "Nota",
        forma: "textarea",
        nombre: "nota",
        filas: 1,
    },
];

export const formularioDetalleAsientoM = [
    {
        id: "transaccionasientom_asiento",
        label: "Asiento",
        forma: "select",
        origen: `${URL_APIC}api/listaasientos/${empresa_id}`, 
        llaves: { id: "id", detalle: "nombre" },
        nombre: "tipoasiento",
        required: true,
    },
    {
        id: "transaccionasientom_monto",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "monto",
        intervalo: "any",
        required: true,
    },
];

export const optnsCobrar = [
    {clave: 1, valor: "Por Cobrar"},
    {clave: 2, valor: "Cobrado"},
];
export const optnsEspecificacion = [
    {clave: 1, valor: "Compras"},
    {clave: 2, valor: "Ventas"},
];
export const formularioDetalleFacturaVenta = [
    {
        id: "trandetallefventa_fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fechatfactura",
        required: true,
        valor: "date",
        n_registro: "fecha",
    },
    {
        id: "trandetallefventa_nfactura",
        label: "# Factura",
        forma: "input",
        tipo: "number",
        nombre: "nfactura",
        required: true,
    },
    {
        id: "trandetallefventa_nautorizacion",
        label: "# Autorizacion",
        forma: "input",
        tipo: "text",
        nombre: "nautorizacion",
        required: true,
    },
    {
        id: "trandetallefventa_codigocontrol",
        label: "#CUF",
        forma: "input",
        tipo: "text",
        nombre: "codigocontrol",
        required: true,
        editar: true,
    },
    {
        id: "trandetallefventa_montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "montofactura",
        intervalo: "any",
        required: true,
    },
    {
        id: "trandetallefventa_tasa0",
        label: "Tasa 0",
        forma: "input",
        tipo: "number",
        nombre: "tasacero",
        intervalo: "any",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefventa_export",
        label: "Export",
        forma: "input",
        tipo: "number",
        nombre: "export",
        intervalo: "any",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefventa_npoliza",
        label: "# Poliza",
        forma: "input",
        tipo: "text",
        nombre: "npoliza",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefventa_iceiecdhotros",
        label: "Iceiecdhotros",
        forma: "input",
        tipo: "number",
        nombre: "iceiecdhotros",
        intervalo: "any",
        required: true,
        valor: "0",
        n_registro: "ice",
    },
    {
        id: "trandetallefventa_descuentobonificacion",
        label: "Descuento Bonificacion",
        forma: "input",
        tipo: "text",
        nombre: "descuentobonificacion",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefventa_especificacion",
        label: "Especificacion",
        forma: "select",
        opciones: optnsEspecificacion, 
        nombre: "especificacion",
        required: true,
        editar: true,
        n_registro: "espesificacion",
    },
    {
        id: "trandetallefventa_cliente",
        label: "Cliente",
        forma: "select",
        origen: `${URL_APIC}api/listaclientes/${empresa_id}`, 
        llaves: { id: "id", detalle: ["nit", "nsocial"] },
        nombre: "cliente",
        required: true,
        n_registro: "idcliente",
    },
    {
        id: "trandetallefventa_cobrar",
        label: "Estado Cobro",
        forma: "select",
        opciones: optnsCobrar, 
        nombre: "cobrar",
        required: true,
        n_registro: "cobrado",
    },
];

export const optnsPagar = [
    {clave: 1, valor: "Por Pagar"},
    {clave: 2, valor: "Pagado"},
];
export const formularioDetalleFacturaCompra = [
    {
        id: "trandetallefcompra_fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fechatfactura",
        required: true,
        valor: "date",
        n_registro: "fecha",
    },
    {
        id: "trandetallefcompra_nfactura",
        label: "# Factura",
        forma: "input",
        tipo: "number",
        nombre: "nfactura",
        required: true,
    },
    {
        id: "trandetallefcompra_nautorizacion",
        label: "# Autorizacion",
        forma: "input",
        tipo: "text",
        nombre: "nautorizacion",
        required: true,
    },
    {
        id: "trandetallefcompra_codigocontrol",
        label: "#CUF",
        forma: "input",
        tipo: "text",
        nombre: "codigocontrol",
        required: true,
        editar: true,
    },
    {
        id: "trandetallefcompra_montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "montofactura",
        intervalo: "any",
        required: true,
    },
    {
        id: "trandetallefcompra_tasa0",
        label: "Tasa 0",
        forma: "input",
        tipo: "number",
        nombre: "tasacero",
        intervalo: "any",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefcompra_export",
        label: "Export",
        forma: "input",
        tipo: "number",
        nombre: "export",
        intervalo: "any",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefcompra_npoliza",
        label: "# Poliza",
        forma: "input",
        tipo: "text",
        nombre: "npoliza",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefcompra_iceiecdhotros",
        label: "Iceiecdhotros",
        forma: "input",
        tipo: "number",
        nombre: "iceiecdhotros",
        intervalo: "any",
        required: true,
        valor: "0",
        n_registro: "ice",
    },
    {
        id: "trandetallefcompra_descuentobonificacion",
        label: "Descuento Bonificacion",
        forma: "input",
        tipo: "text",
        nombre: "descuentobonificacion",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefcompra_especificacion",
        label: "Especificacion",
        forma: "select",
        opciones: optnsEspecificacion, 
        nombre: "especificacion",
        required: true,
        editar: true,
        n_registro: "espesificacion",
    },

    {
        id: "trandetallefcompra_proveedor",
        label: "Proveedor",
        forma: "select",
        origen: `${URL_APIC}api/listaproveedores/${empresa_id}`, 
        llaves: { id: "id", detalle: ["nit", "nombre"] },
        nombre: "cliente",
        required: true,
        n_registro: "idproveedor",
    },
    {
        id: "trandetallefcompra_cobrar",
        label: "Estado Pago",
        forma: "select",
        opciones: optnsPagar, 
        nombre: "pagar",
        required: true,
        valor: 2,
        n_registro: "pagado",
    },
];

export const optnsFacturaTrCobrar = [
    {clave: 1, valor: "Por Cobrar"},
    {clave: 2, valor: "Cobrado"},
];
export const optnsFacturaTrEspecificacion = [
    {clave: 1, valor: "Compras"},
    {clave: 2, valor: "Ventas"},
];

export const formularioFacturasTr = [
    {
        id: "trandetallefventa_fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fechatfactura",
        required: true,
        valor: "date",
        n_registro: "fecha",
    },
    {
        id: "trandetallefventa_nfactura",
        label: "# Factura",
        forma: "input",
        tipo: "number",
        nombre: "nfactura",
        required: true,
    },
    {
        id: "trandetallefventa_nautorizacion",
        label: "# Autorizacion",
        forma: "input",
        tipo: "text",
        nombre: "nautorizacion",
        required: true,
    },
    {
        id: "trandetallefventa_codigocontrol",
        label: "#CUF",
        forma: "input",
        tipo: "text",
        nombre: "codigocontrol",
        required: true,
        editar: true,
    },
    {
        id: "trandetallefventa_montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "montofactura",
        intervalo: "any",
        required: true,
    },
    {
        id: "trandetallefventa_tasa0",
        label: "Tasa 0",
        forma: "input",
        tipo: "number",
        nombre: "tasacero",
        intervalo: "any",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefventa_export",
        label: "Export",
        forma: "input",
        tipo: "number",
        nombre: "export",
        intervalo: "any",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefventa_npoliza",
        label: "# Poliza",
        forma: "input",
        tipo: "text",
        nombre: "npoliza",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefventa_iceiecdhotros",
        label: "Iceiecdhotros",
        forma: "input",
        tipo: "number",
        nombre: "iceiecdhotros",
        intervalo: "any",
        required: true,
        valor: "0",
        n_registro: "ice",
    },
    {
        id: "trandetallefventa_descuentobonificacion",
        label: "Descuento Bonificacion",
        forma: "input",
        tipo: "text",
        nombre: "descuentobonificacion",
        required: true,
        valor: "0",
    },
    {
        id: "trandetallefventa_especificacion",
        label: "Especificacion",
        forma: "select",
        opciones: optnsFacturaTrEspecificacion, 
        nombre: "especificacion",
        required: true,
        editar: true,
        n_registro: "espesificacion",
    },
    {
        id: "trandetallefventa_cliente",
        label: "Cliente",
        forma: "select",
        origen: `${URL_APIC}api/listaclientes/${empresa_id}`, 
        llaves: { id: "id", detalle: ["nit", "nsocial"] },
        nombre: "cliente",
        required: true,
        n_registro: "idcliente",
    },
    {
        id: "trandetallefventa_cobrar",
        label: "Estado Cobro",
        forma: "select",
        opciones: optnsFacturaTrCobrar, 
        nombre: "cobrar",
        required: true,
        n_registro: "cobrado",
    },
    {
        id: "trandetallefventa_cuenta",
        label: "Cuenta",
        forma: "select",
        origen: `${URL_APIC}api/milistaplanes/${empresa_id}`, 
        llaves: { id: "id", detalle: ["numero", "plan"] },
        nombre: "cuenta",
        required: true,
    },
    {
        id: "trandetallefventa_tipo",
        label: "Tipo",
        forma: "select",
        opciones: [
            {clave: 1, valor: "DEBE"},
            {clave: 2, valor: "HABER"},
        ],
        nombre: "tipo",
        required: true,
    },
];