let  a = [
    {
        "idalmacen_material": 19,
        "cantidad": 1452,
        "costo_unitario": 1,
        "peso_neto": 12,
        "costo_envase": 12,
        "cantidad_envases": 121,
        "tipo_envase_idtipo_envase": 38,
        "fecha_caducidad": "2025-01-31",
        "material_idmaterial": 74,
        "codigo_mat": "dasda",
        "medida_idmedida": 53,
        "proveedor_idproveedor": 849,
        "nombre_mat": "semilla",
        "compra_idcompra": 20,
        "nombre_seccion": "Almacen materia prima2",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 28
    },
    {
        "idalmacen_material": 18,
        "cantidad": 529,
        "costo_unitario": 1,
        "peso_neto": 23,
        "costo_envase": 23,
        "cantidad_envases": 23,
        "tipo_envase_idtipo_envase": 58,
        "fecha_caducidad": "2025-01-09",
        "material_idmaterial": 74,
        "codigo_mat": "dasda",
        "medida_idmedida": 53,
        "proveedor_idproveedor": 849,
        "nombre_mat": "semilla",
        "compra_idcompra": 21,
        "nombre_seccion": "Almacen materia prima2",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 29
    },
    {
        "idalmacen_material": 14,
        "cantidad": 113.8,
        "costo_unitario": 0.08333333333333333,
        "peso_neto": 12,
        "costo_envase": 1,
        "cantidad_envases": 12,
        "tipo_envase_idtipo_envase": 31,
        "fecha_caducidad": "2024-12-16",
        "material_idmaterial": 42,
        "codigo_mat": "asLASD32",
        "medida_idmedida": 14,
        "proveedor_idproveedor": 208,
        "nombre_mat": "Sardinas",
        "compra_idcompra": 10,
        "nombre_seccion": "Almacen materia prima",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 25
    },
    {
        "idalmacen_material": 10,
        "cantidad": 63.14,
        "costo_unitario": 0.5,
        "peso_neto": 44,
        "costo_envase": 22,
        "cantidad_envases": 2,
        "tipo_envase_idtipo_envase": 38,
        "fecha_caducidad": "2024-12-14",
        "material_idmaterial": 34,
        "codigo_mat": "A89SS",
        "medida_idmedida": 12,
        "proveedor_idproveedor": 833,
        "nombre_mat": "Aceite",
        "compra_idcompra": 3,
        "nombre_seccion": "Garaje ",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 7
    },
    {
        "idalmacen_material": 9,
        "cantidad": 2607,
        "costo_unitario": 0.053811659192825115,
        "peso_neto": 223,
        "costo_envase": 12,
        "cantidad_envases": 12,
        "tipo_envase_idtipo_envase": 38,
        "fecha_caducidad": "2025-01-05",
        "material_idmaterial": 59,
        "codigo_mat": "PEROH1",
        "medida_idmedida": 12,
        "proveedor_idproveedor": 833,
        "nombre_mat": "prueba12",
        "compra_idcompra": 4,
        "nombre_seccion": "Almacen materia prima",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 6
    },
    {
        "idalmacen_material": 8,
        "cantidad": 529,
        "costo_unitario": 18.347826086956523,
        "peso_neto": 23,
        "costo_envase": 422,
        "cantidad_envases": 23,
        "tipo_envase_idtipo_envase": 30,
        "fecha_caducidad": "2025-02-09",
        "material_idmaterial": 34,
        "codigo_mat": "A89SS",
        "medida_idmedida": 12,
        "proveedor_idproveedor": 833,
        "nombre_mat": "Aceite",
        "compra_idcompra": 4,
        "nombre_seccion": "Garaje ",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 6
    },
    {
        "idalmacen_material": 7,
        "cantidad": 7836.24,
        "costo_unitario": 1,
        "peso_neto": 23,
        "costo_envase": 23,
        "cantidad_envases": 342,
        "tipo_envase_idtipo_envase": 29,
        "fecha_caducidad": "2024-12-29",
        "material_idmaterial": 46,
        "codigo_mat": "PR5",
        "medida_idmedida": 12,
        "proveedor_idproveedor": 833,
        "nombre_mat": "prueba 7",
        "compra_idcompra": 4,
        "nombre_seccion": "Almacen materia prima",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 6
    },
    {
        "idalmacen_material": 6,
        "cantidad": 1575,
        "costo_unitario": 0.6888888888888889,
        "peso_neto": 45,
        "costo_envase": 31,
        "cantidad_envases": 35,
        "tipo_envase_idtipo_envase": 30,
        "fecha_caducidad": "2025-01-26",
        "material_idmaterial": 33,
        "codigo_mat": "Ghsa",
        "medida_idmedida": 14,
        "proveedor_idproveedor": 206,
        "nombre_mat": "harina",
        "compra_idcompra": 5,
        "nombre_seccion": "Almacen materia prima",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 5
    },
    {
        "idalmacen_material": 5,
        "cantidad": 1008,
        "costo_unitario": 0.5,
        "peso_neto": 84,
        "costo_envase": 42,
        "cantidad_envases": 12,
        "tipo_envase_idtipo_envase": 30,
        "fecha_caducidad": "2025-01-05",
        "material_idmaterial": 38,
        "codigo_mat": "AG04L",
        "medida_idmedida": 12,
        "proveedor_idproveedor": 206,
        "nombre_mat": "Agua",
        "compra_idcompra": 5,
        "nombre_seccion": "Garaje ",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 5
    },
    {
        "idalmacen_material": 4,
        "cantidad": 20.61,
        "costo_unitario": 1,
        "peso_neto": 12,
        "costo_envase": 12,
        "cantidad_envases": 2,
        "tipo_envase_idtipo_envase": 29,
        "fecha_caducidad": "2025-02-09",
        "material_idmaterial": 39,
        "codigo_mat": "23242qweq",
        "medida_idmedida": 14,
        "proveedor_idproveedor": 206,
        "nombre_mat": "Comino",
        "compra_idcompra": 6,
        "nombre_seccion": "Almacen materia prima",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 4
    },
    {
        "idalmacen_material": 3,
        "cantidad": 79344,
        "costo_unitario": 0.35964912280701755,
        "peso_neto": 342,
        "costo_envase": 123,
        "cantidad_envases": 232,
        "tipo_envase_idtipo_envase": 30,
        "fecha_caducidad": "2025-03-07",
        "material_idmaterial": 39,
        "codigo_mat": "23242qweq",
        "medida_idmedida": 14,
        "proveedor_idproveedor": 206,
        "nombre_mat": "Comino",
        "compra_idcompra": 8,
        "nombre_seccion": "Almacen materia prima",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 3
    },
    {
        "idalmacen_material": 2,
        "cantidad": 540,
        "costo_unitario": 1.75,
        "peso_neto": 12,
        "costo_envase": 21,
        "cantidad_envases": 45,
        "tipo_envase_idtipo_envase": 38,
        "fecha_caducidad": "2025-05-04",
        "material_idmaterial": 46,
        "codigo_mat": "PR5",
        "medida_idmedida": 12,
        "proveedor_idproveedor": 208,
        "nombre_mat": "prueba 7",
        "compra_idcompra": 9,
        "nombre_seccion": "Almacen materia prima",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 1
    },
    {
        "idalmacen_material": 1,
        "cantidad": 144,
        "costo_unitario": 10.25,
        "peso_neto": 12,
        "costo_envase": 123,
        "cantidad_envases": 12,
        "tipo_envase_idtipo_envase": 29,
        "fecha_caducidad": "2025-02-23",
        "material_idmaterial": 46,
        "codigo_mat": "PR5",
        "medida_idmedida": 12,
        "proveedor_idproveedor": 208,
        "nombre_mat": "prueba 7",
        "compra_idcompra": 7,
        "nombre_seccion": "Almacen materia prima",
        "empresa_idempresa": 50,
        "control_calidad_idcontrol_calidad": 2
    }
]