import { alternarTransaccionYAsiento } from "../../funciones/CrearFormulario.js";
import { CT_URLAPI, getEmpresaId } from "../../funciones/DatosAuxiliares.js";

const URL = CT_URLAPI;
const EMPRESA_ID = getEmpresaId();

// =========================================================
// FORMULARIOS Y FUNCIONES PARA COBRAR FACTURAS
// =========================================================

export const formularioCobrarFactura = ({ editarCajaBanco, crearBotonEliminarArchivo } = {}) => [
    {
        id: "tccobrofactura-lugar",
        label: "Lugar",
        forma: "input",
        tipo: "text",
        nombre: "lugar",
        requerido: true,
    },
    {
        id: "tccobrofactura-fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "fecha",
        requerido: true
    },
    {
        id: "tccobrofactura-persona",
        label: "Persona",
        forma: "input",
        tipo: "text",
        nombre: "persona",
        requerido: true
    },
    {
        id: "tccobrofactura-ci",
        label: "CI",
        forma: "input",
        tipo: "text",
        nombre: "ci",
        requerido: true
    },
    {
        id: "tccobrofactura-montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "monto",
        requerido: true,
        intervalo: "0.01",
        valorMinimo: "0.01",
        editar: false,
    },
    {
        id: "tccobrofactura-concepto",
        label: "Concepto",
        forma: "input",
        tipo: "text",
        nombre: "concepto",
        requerido: "al_crear"
    },
    {
        id: "tccobrofactura-asiento",
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "asiento",
        editar: false,
        callbackInput: alternarTransaccionYAsiento("tccobrofactura"),
    },
    {
        id: "tccobrofactura-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        editar: false,
        callbackInput: alternarTransaccionYAsiento("tccobrofactura"),
    },
    {
        id: "tccobrofactura-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        editar: true,
        requerido: "al_crear",
        llaveRegistro: "transaccion",
    },
    {
        id: "tccobrofactura-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
        desactivado: true,
    },
    {
        id: "tccobrofactura-archivo",
        label: "Adjuntar (archivo)",
        forma: "input",
        tipo: "file",
        nombre: "archivo",
        divInformacion: true,
        opcionesInput: crearBotonEliminarArchivo ? { callback: crearBotonEliminarArchivo } : null,
    },
    {
        id: "tccobrofactura-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Editar Caja/Banco",
        editar: true,
        callbackInput: editarCajaBanco,
        clasesInput: "btn btn-primary w-100 focus-ring",
    },
];

export const formularioCobrarFacturaMultiple = () => [
    {
        id: "tccobrofacturamultiple-fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "fecha",
        requerido: true
    },
    {
        id: "tccobrofacturamultiple-persona",
        label: "Persona",
        forma: "input",
        tipo: "text",
        nombre: "persona",
        requerido: true
    },
    {
        id: "tccobrofacturamultiple-ci",
        label: "CI",
        forma: "input",
        tipo: "text",
        nombre: "ci",
        requerido: true
    },
    {
        id: "tccobrofacturamultiple-montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "monto",
        requerido: true,
        intervalo: "0.01",
        minimo: "0.01",
        soloLectura: "siempre",
    },
    {
        id: "tccobrofacturamultiple-asiento",
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "idasientotipo",
        callbackInput: alternarTransaccionYAsiento("tccobrofacturamultiple"),
    },
    {
        id: "tccobrofacturamultiple-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        callbackInput: alternarTransaccionYAsiento("tccobrofacturamultiple"),
    },
    {
        id: "tccobrofacturamultiple-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
    },
    {
        id: "tccobrofacturamultiple-archivo",
        label: "Adjuntar (archivo)",
        forma: "input",
        tipo: "file",
        nombre: "archivo",
    }
];

// =========================================================
// FORMULARIOS Y FUNCIONES PARA PAGAR FACTURAS
// =========================================================

export const formularioPagarFactura = ({ editarCajaBanco, crearBotonEliminarArchivo } = {}) => [
    {
        id: "tcpagofactura-lugar",
        label: "Lugar",
        forma: "input",
        tipo: "text",
        nombre: "lugar",
        requerido: true,
    },
    {
        id: "tcpagofactura-fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "fecha",
        requerido: true
    },
    {
        id: "tcpagofactura-persona",
        label: "Persona",
        forma: "input",
        tipo: "text",
        nombre: "persona",
        requerido: true
    },
    {
        id: "tcpagofactura-ci",
        label: "CI",
        forma: "input",
        tipo: "text",
        nombre: "ci",
        requerido: true
    },
    {
        id: "tcpagofactura-montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "monto",
        requerido: true,
        intervalo: "0.01",
        valorMinimo: "0.01",
        editar: false,
    },
    {
        id: "tcpagofactura-concepto",
        label: "Concepto",
        forma: "input",
        tipo: "text",
        nombre: "concepto",
        requerido: "al_crear"
    },
    {
        id: "tcpagofactura-asiento",
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "asiento",
        editar: false,
        callbackInput: alternarTransaccionYAsiento("tcpagofactura"),
    },
    {
        id: "tcpagofactura-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        editar: false,
        callbackInput: alternarTransaccionYAsiento("tcpagofactura"),
    },
    {
        id: "tcpagofactura-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        editar: true,
        requerido: "al_crear",
        llaveRegistro: "transaccion",
    },
    {
        id: "tcpagofactura-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
        desactivado: true,
    },
    {
        id: "tcpagofactura-archivo",
        label: "Adjuntar (archivo)",
        forma: "input",
        tipo: "file",
        nombre: "archivo",
        divInformacion: true,
        opcionesInput: crearBotonEliminarArchivo ? { callback: crearBotonEliminarArchivo } : null,
    },
    {
        id: "tcpagofactura-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Editar Caja/Banco",
        editar: true,
        callbackInput: editarCajaBanco,
        clasesInput: "btn btn-primary w-100 focus-ring",
    },
];

export const formularioPagarFacturaMultiple = () => [
    {
        id: "tcpagofacturamultiple-fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "fecha",
        requerido: true
    },
    {
        id: "tcpagofacturamultiple-persona",
        label: "Persona",
        forma: "input",
        tipo: "text",
        nombre: "persona",
        requerido: true
    },
    {
        id: "tcpagofacturamultiple-ci",
        label: "CI",
        forma: "input",
        tipo: "text",
        nombre: "ci",
        requerido: true
    },
    {
        id: "tcpagofacturamultiple-montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "monto",
        requerido: true,
        intervalo: "0.01",
        minimo: "0.01",
        soloLectura: "siempre",
    },
    {
        id: "tcpagofacturamultiple-asiento",
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "idasientotipo",
        callbackInput: alternarTransaccionYAsiento("tcpagofacturamultiple"),
    },
    {
        id: "tcpagofacturamultiple-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        callbackInput: alternarTransaccionYAsiento("tcpagofacturamultiple"),
    },
    {
        id: "tcpagofacturamultiple-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
    },
    {
        id: "tcpagofacturamultiple-archivo",
        label: "Adjuntar (archivo)",
        forma: "input",
        tipo: "file",
        nombre: "archivo",
    }
];

// =========================================================
// FORMULARIOS Y FUNCIONES PARA DOCUMENTOS DE COBRO
// =========================================================

export const formularioCobroContratoConFactura = ({registroContrato}) => [
    {
        id: "tcccobroconfactura-fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "fecha",
        requerido: true,
    },
    {
        id: "tcccobroconfactura-nfactura",
        label: "# Factura",
        forma: "input",
        tipo: "number",
        nombre: "nfactura",
        requerido: true,
    },
    {
        id: "tcccobroconfactura-montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "montofactura",
        intervalo: "0.01",
        valorMinimo: "0.01",
        valor: registroContrato ? registroContrato.precio : undefined,
        requerido: true,
    },
    {
        id: "tcccobroconfactura-cliente",
        label: "Cliente",
        forma: "select",
        urlSolicitud: `${URL}listaclientes/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["nit", "nsocial"] },
        nombre: "cliente",
        llaveRegistro: "idcliente",
        valor: registroContrato ? registroContrato.id_cliente_proveedor : undefined,
        requerido: true,
    },
    {
        id: "tcccobroconfactura-concepto",
        label: "Por concepto de",
        forma: "input",
        tipo: "text",
        nombre: "por_concepto_de",
        requerido: true,
        valor: registroContrato ? registroContrato.concepto_con_formato : undefined,
    },
    {
        id: "tcccobroconfactura-asiento",
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "asiento",
        callbackInput: alternarTransaccionYAsiento("tcccobroconfactura"),
    },
    {
        id: "tcccobroconfactura-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "trans",
        callbackInput: alternarTransaccionYAsiento("tcccobroconfactura"),
    },
    {
        id: "tcccobroconfactura-archivo",
        label: "Adjuntar (archivo)",
        forma: "input",
        tipo: "file",
        nombre: "archivo",
    },
    {
        id: "tcccobroconfactura-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
        desactivado: registroContrato?.precio ? false : true,
    },
    {
        id: "tcccobroconfactura-seccionmasregistros",
        textoBoton: "Más datos ...",
        botonConSeccionModal: [
            {
                id: "tcccobroconfactura-nautorizacion",
                label: "# Autorizacion",
                forma: "input",
                tipo: "text",
                nombre: "nautorizacion",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: "tcccobroconfactura-tasa0",
                label: "Tasa 0",
                forma: "input",
                tipo: "number",
                nombre: "tasacero",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
            },
            {
                id: "tcccobroconfactura-export",
                label: "Export",
                forma: "input",
                tipo: "number",
                nombre: "export",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
            },
            {
                id: "tcccobroconfactura-npoliza",
                label: "# Poliza",
                forma: "input",
                tipo: "text",
                nombre: "npoliza",
                valor: "0",
                valorPorDefecto: "0",
            },
            {
                id: "tcccobroconfactura-iceiecdhotros",
                label: "Iceiecdhotros",
                forma: "input",
                tipo: "number",
                nombre: "iceiecdhotros",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
            },
            {
                id: "tcccobroconfactura-descuentobonificacion",
                label: "Descuento Bonificacion",
                forma: "input",
                tipo: "text",
                nombre: "descuentobonificacion",
                valor: "0",
                valorPorDefecto: "0",
            },
        ]
    }
];

export const formularioCobroContratoConRecibo = ({ registroContrato, editarCajaBanco, crearBotonEliminarArchivo } = {}) => [
    {
        id: "tcccobroconrecibo-nrodoc",
        label: "Nro. doc.",
        forma: "input",
        tipo: "number",
        nombre: "nro_recibo",
        llaveRegistro: "recibo",
        requerido: true
    },
    {
        id: "tcccobroconrecibo-lugar",
        label: "Lugar",
        forma: "input",
        tipo: "text",
        nombre: "lugar",
        valor: registroContrato ? registroContrato.lugar : undefined,
        requerido: true,
    },
    {
        id: "tcccobroconrecibo-fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "fecha",
    },
    {
        id: "tcccobroconrecibo-cliente",
        label: "Cliente",
        forma: "select",
        urlSolicitud: `${URL}listaclientes/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["nit", "nsocial"] },
        nombre: "cliente_proveedor",
        valor: registroContrato ? registroContrato.id_cliente_proveedor : undefined,
        requerido: true,
    },
    {
        id: "tcccobroconrecibo-persona",
        label: "Persona",
        forma: "input",
        tipo: "text",
        nombre: "persona",
        requerido: true,
        valor: registroContrato ? registroContrato.contacto : undefined,
    },
    {
        id: "tcccobroconrecibo-ci",
        label: "CI",
        forma: "input",
        tipo: "text",
        nombre: "ci",
        requerido: true,
        valor: registroContrato ? registroContrato.nro_doc_identidad : undefined,
    },
    {
        id: "tcccobroconrecibo-concepto",
        label: "Concepto",
        forma: "input",
        tipo: "text",
        nombre: "concepto",
        valor: registroContrato ? registroContrato.concepto_con_formato : undefined,
        requerido: "al_crear",
    },
    {
        id: "tcccobroconrecibo-montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "monto",
        intervalo: "0.01",
        valorMinimo: "0.01",
        valor: registroContrato ? registroContrato.precio : undefined,
        editar: false,
        requerido: true,
    },
    {
        id: "tcccobroconrecibo-asiento",
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "asiento",
        editar: false,
        callbackInput: alternarTransaccionYAsiento("tcccobroconrecibo"),
    },
    {
        id: "tcccobroconrecibo-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        editar: false,
        callbackInput: alternarTransaccionYAsiento("tcccobroconrecibo"),
    },
    {
        id: "tcccobroconrecibo-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        editar: true,
        requerido: "al_crear",
        llaveRegistro: "transaccion",
    },
    {
        id: "tcccobroconrecibo-archivo",
        label: "Adjuntar (archivo)",
        forma: "input",
        tipo: "file",
        nombre: "archivo",
        divInformacion: true,
        opcionesInput: crearBotonEliminarArchivo ? { callback: crearBotonEliminarArchivo } : null,
    },
    {
        id: "tcccobroconrecibo-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
        desactivado: registroContrato?.precio ? false : true,
    },
    {
        id: "tcccobroconrecibo-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Editar Caja/Banco",
        editar: true,
        callbackInput: editarCajaBanco,
        clasesInput: "btn btn-primary w-100 focus-ring",
    },
];

// =========================================================
// FORMULARIOS Y FUNCIONES PARA DOCUMENTOS DE PAGO
// =========================================================

export const formularioPagoContratoConFactura = ({ registroContrato }) => [
    {
        id: "tccpagoconfactura-fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "fecha",
        requerido: true,
    },
    {
        id: "tccpagoconfactura-nfactura",
        label: "# Factura",
        forma: "input",
        tipo: "number",
        nombre: "nfactura",
        requerido: true,
    },
    {
        id: "tccpagoconfactura-montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "montofactura",
        intervalo: "0.01",
        valorMinimo: "0.01",
        valor: registroContrato ? registroContrato.precio : undefined,
        requerido: true,
    },
    {
        id: "tccpagoconfactura-proveedor",
        label: "Proveedor",
        forma: "select",
        urlSolicitud: `${URL}listaproveedores/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["nit", "nombre"] },
        nombre: "cliente",
        llaveRegistro: "idcliente",
        valor: registroContrato ? registroContrato.id_cliente_proveedor : undefined,
        requerido: true,
    },
    {
        id: "tccpagoconfactura-concepto",
        label: "Por concepto de",
        forma: "input",
        tipo: "text",
        nombre: "por_concepto_de",
        requerido: true,
        valor: registroContrato ? registroContrato.concepto_con_formato : undefined,
    },
    {
        id: "tccpagoconfactura-asiento",
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "asiento",
        callbackInput: alternarTransaccionYAsiento("tccpagoconfactura"),
    },
    {
        id: "tccpagoconfactura-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "trans",
        callbackInput: alternarTransaccionYAsiento("tccpagoconfactura"),
    },
    {
        id: "tccpagoconfactura-archivo",
        label: "Adjuntar (archivo)",
        forma: "input",
        tipo: "file",
        nombre: "archivo",
    },
    {
        id: "tccpagoconfactura-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
        desactivado: registroContrato?.precio ? false : true,
    },
    {
        id: "tccpagoconfactura-seccionmasregistros",
        textoBoton: "Más datos ...",
        botonConSeccionModal: [
            {
                id: "tccpagoconfactura-nautorizacion",
                label: "# Autorizacion",
                forma: "input",
                tipo: "text",
                nombre: "nautorizacion",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: "tccpagoconfactura-tasa0",
                label: "Tasa 0",
                forma: "input",
                tipo: "number",
                nombre: "tasacero",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
            },
            {
                id: "tccpagoconfactura-export",
                label: "Export",
                forma: "input",
                tipo: "number",
                nombre: "export",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
            },
            {
                id: "tccpagoconfactura-npoliza",
                label: "# Poliza",
                forma: "input",
                tipo: "text",
                nombre: "npoliza",
                valor: "0",
                valorPorDefecto: "0",
            },
            {
                id: "tccpagoconfactura-iceiecdhotros",
                label: "Iceiecdhotros",
                forma: "input",
                tipo: "number",
                nombre: "iceiecdhotros",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
            },
            {
                id: "tccpagoconfactura-descuentobonificacion",
                label: "Descuento Bonificacion",
                forma: "input",
                tipo: "text",
                nombre: "descuentobonificacion",
                valor: "0",
                valorPorDefecto: "0",
            },
        ]
    }
];

export const formularioPagoContratoConRecibo = ({ registroContrato, editarCajaBanco, crearBotonEliminarArchivo } = {}) => [
    {
        id: "tccpagoconrecibo-nrodoc",
        label: "Nro. doc.",
        forma: "input",
        tipo: "number",
        nombre: "nro_recibo",
        llaveRegistro: "recibo",
        requerido: true
    },
    {
        id: "tccpagoconrecibo-lugar",
        label: "Lugar",
        forma: "input",
        tipo: "text",
        nombre: "lugar",
        valor: registroContrato ? registroContrato.lugar : undefined,
        requerido: true,
    },
    {
        id: "tccpagoconrecibo-fecha",
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        valor: "fecha",
    },
    {
        id: "tccpagoconrecibo-proveedor",
        label: "Proveedor",
        forma: "select",
        urlSolicitud: `${URL}listaproveedores/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["nit", "nombre"] },
        nombre: "cliente_proveedor",
        valor: registroContrato ? registroContrato.id_cliente_proveedor : undefined,
        requerido: true,
    },
    {
        id: "tccpagoconrecibo-persona",
        label: "Persona",
        forma: "input",
        tipo: "text",
        nombre: "persona",
        valor: registroContrato ? registroContrato.contacto : undefined,
        requerido: true
    },
    {
        id: "tccpagoconrecibo-ci",
        label: "CI",
        forma: "input",
        tipo: "text",
        nombre: "ci",
        valor: registroContrato ? registroContrato.nro_doc_identidad : undefined,
        requerido: true
    },
    {
        id: "tccpagoconrecibo-concepto",
        label: "Concepto",
        forma: "input",
        tipo: "text",
        nombre: "concepto",
        valor: registroContrato ? registroContrato.concepto_con_formato : undefined,
        requerido: "al_crear",
    },
    {
        id: "tccpagoconrecibo-montofactura",
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "monto",
        intervalo: "0.01",
        valorMinimo: "0.01",
        valor: registroContrato ? registroContrato.precio : undefined,
        editar: false,
        requerido: true,
    },
    {
        id: "tccpagoconrecibo-asiento",
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "asiento",
        editar: false,
        callbackInput: alternarTransaccionYAsiento("tccpagoconrecibo"),
    },
    {
        id: "tccpagoconrecibo-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        editar: false,
        callbackInput: alternarTransaccionYAsiento("tccpagoconrecibo"),
    },
    {
        id: "tccpagoconrecibo-transaccion",
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "idtransaccion",
        editar: true,
        requerido: "al_crear",
        llaveRegistro: "transaccion",
    },
    {
        id: "tccpagoconrecibo-archivo",
        label: "Adjuntar (archivo)",
        forma: "input",
        tipo: "file",
        nombre: "archivo",
        divInformacion: true,
        opcionesInput: crearBotonEliminarArchivo ? { callback: crearBotonEliminarArchivo } : null,
    },
    {
        id: "tccpagoconrecibo-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
        desactivado: registroContrato?.precio ? false : true,
    },
    {
        id: "tccpagoconrecibo-cajasbancos",
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Editar Caja/Banco",
        editar: true,
        callbackInput: editarCajaBanco,
        clasesInput: "btn btn-primary w-100 focus-ring",
    },
];