import { alternarTransaccionYAsiento } from "../../funciones/CrearFormulario.js";
import { CT_URLAPI, getEmpresaId } from "../../funciones/DatosAuxiliares.js";
import { alternarTipoFactYBtnCajaBanco } from "../transacciones/Formularios.js";
const EMPRESA_ID = getEmpresaId();
const URL = CT_URLAPI;

// FACTURACIÓN COBROS
export const optnsFacturaCobrar = [
    {clave: 1, valor: "Por Cobrar"},
    {clave: 2, valor: "Cobrado"},
];
export const formularioTribFacturaCobro = (sufijoId = "tribfacturacobro", estado = true) =>  [
    {
        id: `${sufijoId}-fechat`,
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fechatfactura",
        requerido: true,
        valor: "fecha",
        llaveRegistro: "fecha",
        editar: true,
    },
    {
        id: `${sufijoId}-fecha`,
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        requerido: true,
        valor: "fecha",
        llaveRegistro: "fecha",
        editar: false,
    },
    {
        id: `${sufijoId}-numerofactura`,
        label: "# Factura",
        forma: "input",
        tipo: "number",
        nombre: "nfactura",
        requerido: true,
    },
    {
        id: `${sufijoId}-montofactura`,
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "montofactura",
        intervalo: "0.01",
        valorMinimo: "0.01",
        requerido: true,
    },
    {
        id: `${sufijoId}-cliente`,
        label: "Cliente",
        forma: "select",
        urlSolicitud: `${URL}listaclientes/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["nit", "nsocial"] },
        nombre: "cliente",
        requerido: true,
        llaveRegistro: "idcliente",
    },
    (
        estado ?
            {
                id: `${sufijoId}-estado`,
                label: "Estado Cobro",
                forma: "select",
                opcionesPredefinidas: optnsFacturaCobrar,
                nombre: "cobrado",
                requerido: true,
                callbackInput: alternarTipoFactYBtnCajaBanco(sufijoId),
            }
        : null
    ),
    {
        id: `${sufijoId}-tipofactura`,
        label: "Tipo factura",
        forma: "input",
        tipo: "text",
        nombre: "tipo_factura",
        soloLectura: "siempre",
        ocultar: true,
    },
    {
        id: `${sufijoId}-porconceptode`,
        label: "Por concepto de",
        forma: "input",
        tipo: "text",
        nombre: "por_concepto_de",
        requerido: true,
    },
    {
        id: `${sufijoId}-asiento`,
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "asiento",
        editar: false,
        callbackInput: alternarTransaccionYAsiento(sufijoId),
    },
    {
        id: `${sufijoId}-transaccion`,
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "trans",
        editar: false,
        callbackInput: alternarTransaccionYAsiento(sufijoId),
    },
    {
        id: `${sufijoId}-cajasbancos`,
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
        desactivado: true,
        ocultar: true,
    },
    {
        id: `${sufijoId}-seccionmasregistros`,
        textoBoton: "Más datos ...",
        botonConSeccionModal: [
            {
                id: `${sufijoId}-nautorizacion`,
                label: "# Autorizacion",
                forma: "input",
                tipo: "text",
                nombre: "nautorizacion",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: `${sufijoId}-tasa0`,
                label: "Tasa 0",
                forma: "input",
                tipo: "number",
                nombre: "tasacero",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: `${sufijoId}-export`,
                label: "Export",
                forma: "input",
                tipo: "number",
                nombre: "export",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: `${sufijoId}-npoliza`,
                label: "# Poliza",
                forma: "input",
                tipo: "text",
                nombre: "npoliza",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: `${sufijoId}-iceiecdhotros`,
                label: "Iceiecdhotros",
                forma: "input",
                tipo: "number",
                nombre: "iceiecdhotros",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
                llaveRegistro: "ice",
                requerido: true,
            },
            {
                id: `${sufijoId}-descuentobonificacion`,
                label: "Descuento Bonificacion",
                forma: "input",
                tipo: "text",
                nombre: "descuentobonificacion",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
        ]
    },
];

// FACTURACIÓN PAGOS
export const optnsPagar = [
    {clave: 1, valor: "Por Pagar"},
    {clave: 2, valor: "Pagado"},
];
export const formularioTribFacturaPago = (sufijoId = "tribfacturapago", estado = true) => [
    {
        id: `${sufijoId}-fechat`,
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fechatfactura",
        requerido: true,
        valor: "fecha",
        llaveRegistro: "fecha",
        editar: true,
    },
    {
        id: `${sufijoId}-fecha`,
        label: "Fecha",
        forma: "input",
        tipo: "date",
        nombre: "fecha",
        requerido: true,
        valor: "fecha",
        llaveRegistro: "fecha",
        editar: false,
    },
    {
        id: `${sufijoId}-numerofactura`,
        label: "# Factura",
        forma: "input",
        tipo: "number",
        nombre: "nfactura",
        requerido: true,
    },
    {
        id: `${sufijoId}-montofactura`,
        label: "Monto",
        forma: "input",
        tipo: "number",
        nombre: "montofactura",
        intervalo: "0.01",
        valorMinimo: "0.01",
        requerido: true,
    },
    {
        id: `${sufijoId}-proveedor`,
        label: "Proveedor",
        forma: "select",
        urlSolicitud: `${URL}listaproveedores/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["nit", "nombre"] },
        nombre: "cliente",
        requerido: true,
        llaveRegistro: "idproveedor",
    },
    (
        estado ?
            {
                id: `${sufijoId}-estado`,
                label: "Estado Pago",
                forma: "select",
                opcionesPredefinidas: optnsPagar,
                nombre: "pagado",
                requerido: true,
                callbackInput: alternarTipoFactYBtnCajaBanco(sufijoId),
            }
        : null
    ),
    {
        id: `${sufijoId}-tipofactura`,
        label: "Tipo factura",
        forma: "input",
        tipo: "text",
        nombre: "tipo_factura",
        soloLectura: "siempre",
        ocultar: true,
    },
    {
        id: `${sufijoId}-porconceptode`,
        label: "Por concepto de",
        forma: "input",
        tipo: "text",
        nombre: "por_concepto_de",
        requerido: true,
    },
    {
        id: `${sufijoId}-asiento`,
        label: "Generar nueva Transacción",
        forma: "select",
        urlSolicitud: `${URL}listaasientos/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: "nombre"},
        nombre: "asiento",
        editar: false,
        callbackInput: alternarTransaccionYAsiento(sufijoId),
    },
    {
        id: `${sufijoId}-transaccion`,
        label: "Vincular a Trans. existente",
        forma: "select",
        urlSolicitud: `${URL}listatransacciones/${EMPRESA_ID}`,
        llavesOpciones: { valor: "id", detalle: ["ntransaccion", "glosa"] },
        nombre: "trans",
        editar: false,
        callbackInput: alternarTransaccionYAsiento(sufijoId),
    },
    {
        id: `${sufijoId}-cajasbancos`,
        label: "Cajas y Bancos",
        forma: "button",
        nombre: "Asignar Caja/Banco",
        editar: false,
        desactivado: true,
        ocultar: true,
    },
    {
        id: `${sufijoId}-seccionmasregistros`,
        textoBoton: "Más datos ...",
        botonConSeccionModal: [
            {
                id: `${sufijoId}-nautorizacion`,
                label: "# Autorizacion",
                forma: "input",
                tipo: "text",
                nombre: "nautorizacion",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: `${sufijoId}-tasa0`,
                label: "Tasa 0",
                forma: "input",
                tipo: "number",
                nombre: "tasacero",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: `${sufijoId}-export`,
                label: "Export",
                forma: "input",
                tipo: "number",
                nombre: "export",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: `${sufijoId}-npoliza`,
                label: "# Poliza",
                forma: "input",
                tipo: "text",
                nombre: "npoliza",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
            {
                id: `${sufijoId}-iceiecdhotros`,
                label: "Iceiecdhotros",
                forma: "input",
                tipo: "number",
                nombre: "iceiecdhotros",
                intervalo: "any",
                valor: "0",
                valorPorDefecto: "0",
                llaveRegistro: "ice",
                requerido: true,
            },
            {
                id: `${sufijoId}-descuentobonificacion`,
                label: "Descuento Bonificacion",
                forma: "input",
                tipo: "text",
                nombre: "descuentobonificacion",
                valor: "0",
                valorPorDefecto: "0",
                requerido: true,
            },
        ]
    },
];